/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {

    private final Sol solution = new Sol();

    @Test 
    public void threeNumsFiveSteps_ReturnFour() {
        assertEquals(4, solution.minOperations(new int[]{3,9,7}, 5));
    }

    @Test
    public void threeNumsFourSteps_ReturnZero() {
        assertEquals(0, solution.minOperations(new int[]{4,1,3}, 4));
    }

    @Test
    public void twoNumsSixSteps_ReturnFive() {
        assertEquals(5, solution.minOperations(new int[]{3,2}, 6));
    }
}
