/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {

    private final Solution solution = new Solution();

    @Test 
    public void testHelloString_Return13() {
        assertEquals(13, solution.scoreOfString("hello"));
    }

    @Test
    public void testNullString() {
        assertEquals(-1, solution.scoreOfString(null));
    }

    @Test
    public void testEmptyString_Returns0() {
        assertEquals(0, solution.scoreOfString(""));
    }

    @Test
    public void testzazString_Return50(){
        assertEquals(50, solution.scoreOfString("zaz"));
    }

    @Test
    public void testSpecialCharactersIgnore() {
        assertEquals(0, solution.scoreOfString("\t\n"));
    }
}
