/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

class SolutionTest {

    private final Solution solution = new Solution();

    @Test
    public void returnNotNull() {
        assertNotNull(solution.findDegrees(new int[][]{{0,1,1}, {1,0,1}, {1,1,0}}));
    }

    @Test
    public void testThreeFullyConnectedVertices() {
        assertArrayEquals(new int[]{2, 2, 2}, solution.findDegrees(new int[][]{{0,1,1}, {1,0,1}, {1,1,0}}));
    }

    @Test
    public void testTwoOfThreeVertcesConnected() {
        assertArrayEquals(new int[]{1, 1, 0}, solution.findDegrees(new int[][]{{0,1,0}, {1,0,0}, {0,0,0}}));
    }

    @Test
    public void noVerticesConnected() {
        assertArrayEquals(new int[] {0, 0, 0}, solution.findDegrees(new int[][]{{0,0,0}, {0,0,0}, {0,0,0}}));
    }

    @Test
    public void passNoArray() {
        assertNull(solution.findDegrees(null));
    }
}
